# Generated by Django 5.0.3 on 2025-07-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajoneras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre4', models.CharField(max_length=100)),
                ('descripcion4', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('precio4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen4', models.ImageField(upload_to='uploads/productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Escritorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre5', models.CharField(max_length=100)),
                ('descripcion5', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('precio5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen5', models.ImageField(upload_to='uploads/productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=100)),
                ('descripcion1', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('precio1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen1', models.ImageField(upload_to='uploads/productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Sillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre2', models.CharField(max_length=100)),
                ('descripcion2', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('precio2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen2', models.ImageField(upload_to='uploads/productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Utensilios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre6', models.CharField(max_length=100)),
                ('descripcion6', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('precio6', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen6', models.ImageField(upload_to='uploads/productos/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Armarios',
        ),
        migrations.RenameField(
            model_name='armarios',
            old_name='descripcion',
            new_name='descripcion3',
        ),
        migrations.RenameField(
            model_name='armarios',
            old_name='imagen',
            new_name='imagen3',
        ),
        migrations.RenameField(
            model_name='armarios',
            old_name='nombre',
            new_name='nombre3',
        ),
        migrations.RenameField(
            model_name='armarios',
            old_name='precio',
            new_name='precio3',
        ),
    ]
