# Generated by Django 5.0.3 on 2025-08-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cajoneras_escritorios_mesas_sillas_utensilios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameCliente', models.CharField(max_length=100, unique=True)),
                ('passwordCliente', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
