# Generated by Django 5.2.5 on 2025-09-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userclientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameEmpresa', models.CharField(max_length=100, unique=True)),
                ('passwordEmpresa', models.CharField(max_length=100)),
            ],
        ),
    ]
