# Generated by Django 5.2.5 on 2025-09-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
