# Generated by Django 5.2.5 on 2025-10-13 23:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='empresa_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userempresa'),
        ),
        migrations.AddField(
            model_name='idea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='idea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/ideas/'),
        ),
    ]
