# Generated by Django 5.2.5 on 2025-10-14 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_status_fields'),
        ('core', '0009_userclientes_is_active_userempresa_is_active'),
    ]

    operations = [
    ]
