# Generated by Django 5.2.5 on 2025-10-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20251013_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclientes',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userclientes',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userempresa',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userempresa',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
