# Generated by Django 5.2.5 on 2025-11-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userclientes_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='modelo_3d',
            field=models.FileField(blank=True, null=True, upload_to='uploads/ideas/modelos3d/'),
        ),
    ]
