# Generated by Django 5.2.5 on 2025-11-03 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_idea_modelo_3d'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdmin',
        ),
    ]
