# Generated by Django 5.2.5 on 2025-11-03 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_useradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclientes',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/perfiles/'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.userclientes')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
