# Generated by Django 5.2.5 on 2025-11-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('notas_adicionales', models.TextField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('empacado', 'Empacado'), ('enviado', 'Enviado'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='procesando', max_length=20)),
                ('numero_seguimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('productos', models.TextField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.userclientes')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='core.pago')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
