# Generated by Django 5.2.5 on 2025-11-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_pedido_ciudad_alter_pedido_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armarios',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cajoneras',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escritorios',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesas',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sillas',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utensilios',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
