# Generated by Django 5.2.5 on 2025-11-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_armarios_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='fecha_permiso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='mensaje_empresa',
            field=models.TextField(blank=True, help_text='Mensaje de la empresa al cliente sobre la idea', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='permiso_publicacion',
            field=models.BooleanField(default=False, help_text='Permiso del cliente para publicar como producto'),
        ),
        migrations.AddField(
            model_name='idea',
            name='publicada_como_producto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='respuesta_cliente',
            field=models.TextField(blank=True, help_text='Respuesta del cliente a la empresa', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
    ]
