# Generated by Django 5.2.7 on 2025-11-12 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_idea_fecha_permiso_idea_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente_tipo', models.CharField(choices=[('empresa', 'Empresa'), ('cliente', 'Cliente')], max_length=10)),
                ('remitente_nombre', models.CharField(max_length=100)),
                ('mensaje', models.TextField(max_length=1000)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('es_solicitud_permiso', models.BooleanField(default=False)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.idea')),
            ],
            options={
                'ordering': ['fecha_envio'],
            },
        ),
    ]
