# Generated by Django 5.2.5 on 2025-11-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_mensajeidea'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente_tipo', models.CharField(choices=[('empresa', 'Empresa'), ('cliente', 'Cliente')], max_length=10)),
                ('remitente_nombre', models.CharField(max_length=100)),
                ('mensaje', models.TextField(max_length=1000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='uploads/chat_pagos/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.pago')),
            ],
            options={
                'ordering': ['fecha_envio'],
            },
        ),
    ]
