# Generated by Django 5.2.5 on 2025-11-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_mensajepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('finalizada', 'Finalizada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
