# Generated by Django 5.2.5 on 2025-12-04 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_armarios_is_active_cajoneras_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclientes',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userclientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{7,15}$', 'Ingrese un número de teléfono válido (solo números, 7-15 dígitos)')]),
        ),
    ]
