# Generated by Django 5.2.5 on 2025-12-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_userclientes_email_alter_userclientes_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='userempresa',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
