# Generated by Django 5.2.5 on 2025-12-08 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userempresa_2fa_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_tipo', models.CharField(max_length=20)),
                ('producto_id', models.IntegerField()),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to='core.userclientes')),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('usuario', 'producto_tipo', 'producto_id')},
            },
        ),
    ]
