# Generated by Django 5.0.3 on 2025-07-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
