# Generated by Django 5.2.5 on 2025-12-12 02:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El número debe tener el formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número debe tener el formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono Alternativo')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('nombre_representante', models.CharField(max_length=200, verbose_name='Nombre del Representante Legal')),
                ('cedula_representante', models.CharField(max_length=20, verbose_name='Cédula del Representante')),
                ('email_representante', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email del Representante')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/empresas/logos/', verbose_name='Logo')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA Habilitado')),
                ('two_factor_code', models.CharField(blank=True, max_length=6, null=True)),
                ('two_factor_code_expires', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empresa Registrada',
                'verbose_name_plural': 'Empresas Registradas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
