# Generated by Django 5.2.5 on 2025-12-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaregistrada',
            name='email_2fa',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para 2FA'),
        ),
        migrations.AddField(
            model_name='empresaregistrada',
            name='telefono_2fa',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Teléfono para 2FA'),
        ),
    ]
