# Generated by Django 5.2.5 on 2025-12-12 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0002_empresaregistrada_email_2fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaregistrada',
            name='cedula_representante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del Representante'),
        ),
        migrations.AlterField(
            model_name='empresaregistrada',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='empresaregistrada',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='empresaregistrada',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='empresaregistrada',
            name='email_representante',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email del Representante'),
        ),
        migrations.AlterField(
            model_name='empresaregistrada',
            name='nombre_representante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Representante Legal'),
        ),
        migrations.AlterField(
            model_name='empresaregistrada',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='empresaregistrada',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número debe tener el formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
    ]
